language: perl
sudo: false

addons:
  apt:
    packages:
    - libsnmp-dev
    - snmp-mibs-downloader

before_install:
    - eval $(curl https://travis-perl.github.io/init) --auto

perl:
    - "5.10"
    - "5.8"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

matrix:
  include:
    - perl: 5.18
      env:
        - COVERAGE=1 COVERAGE_OPTS='-ignore_re /CORE/\w+\.h$'
  allow_failures:
    - perl: blead       # ignore failures for blead perl
    - perl: dev         # ignore failures for dev perl
