language: perl
sudo: true

before_install:
    - "sudo apt-get -yq update"
    - "sudo apt-get -yq install libsnmp-dev"
    - eval $(curl https://travis-perl.github.io/init) --auto

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
    - perl: dev         # ignore failures for dev perl
